name: ecg
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23
  - cudatoolkit=11.2
  - cudnn=8.1
  - scipy
  - scikit-learn
  - seaborn
  - jupyterlab
  - matplotlib
  - pip:
    - tensorflow==2.10
    - wfdb
